version: '3.3'
 
services:
 
  amq:
    image: vromero/activemq-artemis:latest-alpine
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: amq
      ARTEMIS_PASSWORD: amq
    ports:
      - 8161:8161
      - 61616:61616
